-- Migration: Add lecture_plan field to lecture table
-- This field stores the comprehensive teaching plan generated for each lecture
-- including activities, quizzes, timing, and pedagogical strategies

-- Add lecture_plan column to lecture table
ALTER TABLE public.lecture
ADD COLUMN IF NOT EXISTS lecture_plan TEXT;

-- Add comment to explain the field
COMMENT ON COLUMN public.lecture.lecture_plan IS 'Comprehensive teaching plan in JSON format including activities, quizzes, discussion questions, timing, and pedagogical strategies generated by AI';

